---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insurance-claims
  namespace: insurance-claims
  labels:
    app: insurance-claims
    component: service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insurance-claims
  namespace: insurance-claims-staging
  labels:
    app: insurance-claims
    component: service-account
    env: staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: insurance-claims
  name: insurance-claims-role
  labels:
    app: insurance-claims
    component: rbac
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: insurance-claims-staging
  name: insurance-claims-role
  labels:
    app: insurance-claims
    component: rbac
    env: staging
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: insurance-claims-rolebinding
  namespace: insurance-claims
  labels:
    app: insurance-claims
    component: rbac
subjects:
- kind: ServiceAccount
  name: insurance-claims
  namespace: insurance-claims
roleRef:
  kind: Role
  name: insurance-claims-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: insurance-claims-rolebinding
  namespace: insurance-claims-staging
  labels:
    app: insurance-claims
    component: rbac
    env: staging
subjects:
- kind: ServiceAccount
  name: insurance-claims
  namespace: insurance-claims-staging
roleRef:
  kind: Role
  name: insurance-claims-role
  apiGroup: rbac.authorization.k8s.io
